//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeVillageStats.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public long idPerson { get; set; }
        public string lastName { get; set; }
        public string firstName { get; set; }
        public string gender { get; set; }
        public string address { get; set; }
        public Nullable<long> neighborhood { get; set; }
        public string telephone { get; set; }
        public string email { get; set; }
        public string baptise { get; set; }
        public Nullable<int> age { get; set; }
    
        public virtual NeighborHood NeighborHood1 { get; set; }
    }
}
